diff --git a/Dockerfile b/Dockerfile
index 30b6685..354b08b 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM ubuntu:20.04
+FROM nvidia/cuda:11.7.0-base-ubuntu20.04
 
 ARG S6_OVERLAY_VERSION=v2.2.0.3
 ARG S6_OVERLAY_ARCH=amd64
@@ -14,8 +14,9 @@ ENTRYPOINT ["/init"]
 
 RUN \
 # Update and get dependencies
-    apt-get update && \
-    apt-get install -y \
+    apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub && \
+    apt update && \
+    apt install -y --no-install-recommends \
       tzdata \
       curl \
       xmlstarlet \
@@ -23,6 +24,8 @@ RUN \
       unrar \
       beignet-opencl-icd \
       ocl-icd-libopencl1 \
+      libnvidia-encode-515 \
+      libnvidia-decode-515 \
     && \
     \
 # Fetch and extract S6 overlay
